project_id = "eyuzakziwgkaogiqfhro"

[functions.sync-data]
verify_jwt = false

[functions.generate-budget-forecast]
verify_jwt = true

[functions.scan-receipt]
verify_jwt = true

[functions.scan-business-card]
verify_jwt = true

[functions.get-mapbox-token]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = true

[functions.transcribe-audio]
verify_jwt = true
